# Default values for deployments.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: nginx

env:
  hamed: salim
  asqar: farhadi

service:
  type: ClusterIP
  ports: 
    main:
      port: 80
      protocol: TCP 

ingress:
  ingressClassName: nginx
  rules:
    main:
      host: hamed.com
      pathType: Prefix
      path: "/"
      port: 80