{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name}}
    app.kubernetes.io/name: {{ .Release.Name}}
    release: monitoring
  name: {{ .Release.Name}}
  namespace: {{ .Release.Namespace}}
spec:
  endpoints:
  - interval: 30s
    path: {{ .Values.metrics.path}}
    port: {{ .Release.Name}}-service-metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Name}}
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance:  {{ .Release.Name}}
      app.kubernetes.io/name:  {{ .Release.Name}}
{{- end }}