apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-service
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $k, $v := .Values.service.ports }}
      - name: {{ $k }}
        port: {{ $v.port }}
        protocol: {{ default "TCP" $v.protocol }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}
